# Generated by Django 5.0.1 on 2025-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dropoff_address",
            field=models.TextField(
                blank=True, default="", help_text="Dropoff location address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, default="", help_text="Additional notes for the order"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_address",
            field=models.TextField(
                blank=True, default="", help_text="Pickup location address"
            ),
        ),
    ]
