# Generated by Django 5.0.1 on 2025-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", help_text="User's phone number", max_length=20
            ),
        ),
    ]
