# Generated by Django 5.0.1 on 2025-12-02 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Driver's current latitude",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Driver's current longitude",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False, help_text="Whether driver is currently online"
                    ),
                ),
                (
                    "is_busy",
                    models.BooleanField(
                        default=False,
                        help_text="Whether driver is currently busy with an order",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, help_text="Vehicle model", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_online_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "db_table": "drivers",
                "ordering": ["-created_at"],
            },
        ),
    ]
