# Generated by Django 5.0.1 on 2025-12-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "DRIVER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["is_online", "is_busy"], name="drivers_is_onli_5499c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["latitude", "longitude"], name="drivers_latitud_cba97b_idx"
            ),
        ),
    ]
