# Generated by Django 5.0.1 on 2025-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_model",
            field=models.CharField(
                blank=True, default="", help_text="Vehicle model", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vehicle registration number",
                max_length=20,
            ),
        ),
    ]
